/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogoImpressaoCondomino.java
 *
 * Created on Oct 25, 2012, 11:14:47 AM
 */
package condominioPlus.apresentacao.condomino;

import condominioPlus.negocio.Anotacao;
import condominioPlus.negocio.Condominio;
import condominioPlus.relatorios.TipoRelatorio;
import condominioPlus.util.Relatorios;
import java.awt.event.ActionEvent;
import logicpoint.apresentacao.ControladorEventosGenerico;

/**
 *
 * @author Administrador
 */
public class DialogoImpressaoCondomino extends javax.swing.JDialog {

    private Condominio condominio;
    private ControladorDeEventos controlador;

    /** Creates new form DialogoImpressaoCondomino */
    public DialogoImpressaoCondomino(Condominio condominio, java.awt.Frame pai, boolean modal) {
        super(pai, modal);
        this.condominio = condominio;
        initComponents();
        controlador = new ControladorDeEventos();
        this.setLocationRelativeTo(null);
    }

    private void imprimir() {
        if (chkRelacaoProprietarios.isSelected()) {
            new Relatorios().imprimirRelacaoProprietarios(true, null, condominio, condominio.getUnidades(), TipoRelatorio.RELACAO_PROPRIETARIOS);
        }
        if (chkRelacaoProprietariosEmail.isSelected()) {
            new Relatorios().imprimirRelacaoProprietarios(true, null, condominio, condominio.getUnidades(), TipoRelatorio.RELACAO_PROPRIETARIOS_EMAIL);
        }
        if (chkRelacaoProprietariosUnidade.isSelected()) {
            new Relatorios().imprimirRelacaoProprietarios(true, null, condominio, condominio.getUnidades(), TipoRelatorio.RELACAO_PROPRIETARIOS_UNIDADE);
        }
        if (chkFracaoIdeal.isSelected()) {
            new Relatorios().imprimirListaFracoesIdeais(condominio, condominio.getUnidades());
        }
//        fechar();
    }

    private void cancelar() {
        fechar();
    }

    private void fechar() {
        super.dispose();
    }

    @Override
    public void dispose() {
        cancelar();
    }

    private class ControladorDeEventos extends ControladorEventosGenerico {

        @Override
        public void configurar() {
            put(Anotacao.class, DialogoImpressaoCondomino.this);

            btnOk.addActionListener(this);
            btnCancelar.addActionListener(this);
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            source = e.getSource();
            if (source == btnOk) {
                imprimir();
            } else if (source == btnCancelar) {
                cancelar();
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        chkRelacaoProprietarios = new javax.swing.JCheckBox();
        chkRelacaoProprietariosEmail = new javax.swing.JCheckBox();
        chkRelacaoProprietariosUnidade = new javax.swing.JCheckBox();
        chkFracaoIdeal = new javax.swing.JCheckBox();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Impressão Condôminos");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        chkRelacaoProprietarios.setText("Relação Proprietários");

        chkRelacaoProprietariosEmail.setText("Relação Proprietários - Email");

        chkRelacaoProprietariosUnidade.setText("Relação Proprietários - Unidade");

        chkFracaoIdeal.setText("Relação Frações Ideais");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkRelacaoProprietarios)
                    .addComponent(chkRelacaoProprietariosEmail)
                    .addComponent(chkRelacaoProprietariosUnidade)
                    .addComponent(chkFracaoIdeal))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkRelacaoProprietarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkRelacaoProprietariosEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkRelacaoProprietariosUnidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkFracaoIdeal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnOk.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominioPlus/recursos/imagens/ok.GIF"))); // NOI18N
        btnOk.setMaximumSize(new java.awt.Dimension(32, 32));
        btnOk.setMinimumSize(new java.awt.Dimension(32, 32));
        btnOk.setPreferredSize(new java.awt.Dimension(32, 32));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominioPlus/recursos/imagens/remover.gif"))); // NOI18N
        btnCancelar.setMaximumSize(new java.awt.Dimension(32, 32));
        btnCancelar.setMinimumSize(new java.awt.Dimension(32, 32));
        btnCancelar.setPreferredSize(new java.awt.Dimension(32, 32));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JCheckBox chkFracaoIdeal;
    private javax.swing.JCheckBox chkRelacaoProprietarios;
    private javax.swing.JCheckBox chkRelacaoProprietariosEmail;
    private javax.swing.JCheckBox chkRelacaoProprietariosUnidade;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
