/*
 * TelaBanco.java
 *
 * Created on 7 de Novembro de 2007, 10:01
 */
package condominioPlus.apresentacao;

import condominioPlus.apresentacao.financeiro.DialogoBanco;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import condominioPlus.negocio.Banco;
import logicpoint.apresentacao.ApresentacaoUtil;
import logicpoint.apresentacao.ControladorEventosGenerico;
import logicpoint.persistencia.DAO;
import logicpoint.util.ListaModelo;

/**
 *
 * @author  USUARIO
 */
public class TelaBanco extends javax.swing.JInternalFrame {

    private Banco banco;
    /** Creates new form TelaBanco */
    public TelaBanco() {
        initComponents();
        new ControladorEventos();
        lista.setModel(new ListaModelo<Banco>());
        ((ListaModelo<Banco>) lista.getModel()).setOrdenada(true);
        listar();
    }

    private ListaModelo<Banco> getModelo() {
        return (ListaModelo<Banco>) lista.getModel();
    }

    private void listar() {
        try {
            getModelo().setObjetos(new DAO().listar(Banco.class));
        } catch (Exception ex) {
            ApresentacaoUtil.exibirErro(ex.getMessage(), this);
        }
    }

    private void adicionar() {
        banco = DialogoBanco.getBanco(new Banco(), TelaPrincipal.getInstancia(), true);
        if (banco != null && !(banco.getNomeBanco().equals(""))) {
            for (Banco b : getModelo().getObjetos()) {
                if (b.getNomeBanco().equalsIgnoreCase(banco.getNomeBanco())) {
                    ApresentacaoUtil.exibirAdvertencia("O banco digitado já encontra-se cadastrado", this);
                    return;
                }
            }
            try {
                new DAO().salvar(banco);
            } catch (Exception ex) {
                ApresentacaoUtil.exibirErro(ex.getMessage(), this);
            }
            listar();
        } else {
            return;
        }
    }

    private void editar() {
        banco = getModelo().getObjeto(lista);
        if (banco != null) {
            DialogoBanco.getBanco(banco, TelaPrincipal.getInstancia(), true);
            }else{
            ApresentacaoUtil.exibirAdvertencia("Você precisa selecionar um banco para editá-lo!", this);
        }
    }

    private void remover() {
        banco = getModelo().getObjeto(lista);        
        if (banco == null || ApresentacaoUtil.perguntar("Deseja realmente remover o banco " + banco.getNomeBanco() + "?",
                new String[]{"Sim", "Não"}, this) != ApresentacaoUtil.RESPOSTA1) {
            return;
        }
        try {
            new DAO().remover(banco);
            ApresentacaoUtil.exibirInformacao("Banco removido com sucesso!", this);
        } catch (Exception ex) {
            ApresentacaoUtil.exibirErro(ex.getMessage(), this);
        }

        listar();
    }

    private class ControladorEventos extends ControladorEventosGenerico {

        @Override
        public void configurar() {
            lista.addMouseListener(this);
            btnAdicionar.addActionListener(this);
            btnEditar.addActionListener(this);
            btnRemover.addActionListener(this);
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            source = e.getSource();
            if (source == btnAdicionar) {
                adicionar();
            } else if (source == btnEditar) {
                editar();
            } else if (source == btnRemover) {
                remover();
            }
            source = null;
        }
        
        @Override
        public void mouseClicked(MouseEvent e) {
            if (e.getSource() == lista && e.getClickCount() >= 2) {
                editar();
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();

        setClosable(true);
        setTitle("Bancos");
        setVisible(true);

        jScrollPane1.setViewportView(lista);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominioPlus/recursos/imagens/adicionar.gif"))); // NOI18N
        btnAdicionar.setToolTipText("Adicionar");
        btnAdicionar.setPreferredSize(new java.awt.Dimension(28, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        jPanel1.add(btnAdicionar, gridBagConstraints);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominioPlus/recursos/imagens/atualizar.gif"))); // NOI18N
        btnEditar.setToolTipText("Editar");
        btnEditar.setPreferredSize(new java.awt.Dimension(28, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        jPanel1.add(btnEditar, gridBagConstraints);

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/condominioPlus/recursos/imagens/lixeira.gif"))); // NOI18N
        btnRemover.setToolTipText("Remover");
        btnRemover.setPreferredSize(new java.awt.Dimension(28, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        jPanel1.add(btnRemover, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lista;
    // End of variables declaration//GEN-END:variables

}
